apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  local.yaml: |+
    service:
      {{ if .Values.service.port -}}
      port: {{ .Values.service.port }}
      {{- end }}
    postgres:
      {{ if .Values.postgres.host -}}
      host: {{ .Values.postgres.host }}
      {{- end }}
      {{ if .Values.postgres.port -}}
      port: {{ .Values.postgres.port }}
      {{- end }}
      {{ if .Values.postgres.name -}}
      name: {{ .Values.postgres.name }}
      {{- end }}
      {{ if .Values.postgres.username -}}
      username: {{ .Values.postgres.username }}
      {{- end }}
      {{ if .Values.postgres.password -}}
      password: {{ .Values.postgres.password }}
      {{- end }}
    redis:
      {{ if .Values.redis.url -}}
      url: {{ .Values.redis.url }}
      {{- end }}
    log:
      {{ if .Values.log.level -}}
      level: {{ .Values.log.level }}
      {{- end }}
      {{ if .Values.log.handler -}}
      handler: {{ .Values.log.handler }}
      {{- end }}
