apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  local.yaml: |+
    service:
      {{ if .Values.service.port -}}
      port: {{ .Values.service.port }}
      {{- end }}
    db:
      {{ if .Values.database.host -}}
      host: {{ .Values.database.host }}
      {{- end }}
      {{ if .Values.database.port -}}
      port: {{ .Values.database.port }}
      {{- end }}
      {{ if .Values.database.name -}}
      name: {{ .Values.database.name }}
      {{- end }}
      {{ if .Values.database.username -}}
      username: {{ .Values.database.username }}
      {{- end }}
      {{ if .Values.database.password -}}
      password: {{ .Values.database.password }}
      {{- end }}
