// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: bill_create.sql

package spinusdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMmBill = `-- name: CreateMmBill :one
INSERT INTO mm_bill (
	fk_mm,
	subid,
	max_day_diff,
	begin_date,
	end_date,
	energy_consum,
	consum_energy_price,
	service_price,
	advance_price,
	from_fin_balance,
	to_pay,
	status
) SELECT $1, COALESCE(MAX(subid), 0) + 1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
	FROM mm_bill
	WHERE fk_mm = $1
RETURNING id, fk_mm, subid, max_day_diff, begin_date, end_date, energy_consum, consum_energy_price, service_price, advance_price, from_fin_balance, to_pay, status
`

type CreateMmBillParams struct {
	FkMm              int32
	MaxDayDiff        int32
	BeginDate         pgtype.Date
	EndDate           pgtype.Date
	EnergyConsum      float64
	ConsumEnergyPrice float64
	ServicePrice      pgtype.Float8
	AdvancePrice      float64
	FromFinBalance    float64
	ToPay             float64
	Status            MmBillStatus
}

func (q *Queries) CreateMmBill(ctx context.Context, arg CreateMmBillParams) (MmBill, error) {
	row := q.db.QueryRow(ctx, createMmBill,
		arg.FkMm,
		arg.MaxDayDiff,
		arg.BeginDate,
		arg.EndDate,
		arg.EnergyConsum,
		arg.ConsumEnergyPrice,
		arg.ServicePrice,
		arg.AdvancePrice,
		arg.FromFinBalance,
		arg.ToPay,
		arg.Status,
	)
	var i MmBill
	err := row.Scan(
		&i.ID,
		&i.FkMm,
		&i.Subid,
		&i.MaxDayDiff,
		&i.BeginDate,
		&i.EndDate,
		&i.EnergyConsum,
		&i.ConsumEnergyPrice,
		&i.ServicePrice,
		&i.AdvancePrice,
		&i.FromFinBalance,
		&i.ToPay,
		&i.Status,
	)
	return i, err
}

const createMmBillPeriod = `-- name: CreateMmBillPeriod :one
INSERT INTO mm_bill_period (
	fk_mm_bill,
	subid,
	begin_date,
	end_date,
	begin_rdg_val,
	end_rdg_val,
	energy_consum,
	consum_energy_price,
	service_price,
	advance_price,
	total_price
) SELECT $1, COALESCE(MAX(subid), 0) + 1, $2, $3, $4, $5, $6, $7, $8, $9, $10
	FROM mm_bill_period
	WHERE fk_mm_bill = $1
RETURNING id, fk_mm_bill, subid, begin_date, end_date, begin_rdg_val, end_rdg_val, energy_consum, consum_energy_price, service_price, advance_price, total_price
`

type CreateMmBillPeriodParams struct {
	FkMmBill          int32
	BeginDate         pgtype.Date
	EndDate           pgtype.Date
	BeginRdgVal       float64
	EndRdgVal         float64
	EnergyConsum      float64
	ConsumEnergyPrice float64
	ServicePrice      pgtype.Float8
	AdvancePrice      float64
	TotalPrice        float64
}

func (q *Queries) CreateMmBillPeriod(ctx context.Context, arg CreateMmBillPeriodParams) (MmBillPeriod, error) {
	row := q.db.QueryRow(ctx, createMmBillPeriod,
		arg.FkMmBill,
		arg.BeginDate,
		arg.EndDate,
		arg.BeginRdgVal,
		arg.EndRdgVal,
		arg.EnergyConsum,
		arg.ConsumEnergyPrice,
		arg.ServicePrice,
		arg.AdvancePrice,
		arg.TotalPrice,
	)
	var i MmBillPeriod
	err := row.Scan(
		&i.ID,
		&i.FkMmBill,
		&i.Subid,
		&i.BeginDate,
		&i.EndDate,
		&i.BeginRdgVal,
		&i.EndRdgVal,
		&i.EnergyConsum,
		&i.ConsumEnergyPrice,
		&i.ServicePrice,
		&i.AdvancePrice,
		&i.TotalPrice,
	)
	return i, err
}

const createSmBill = `-- name: CreateSmBill :one
INSERT INTO sm_bill (
	fk_sm,
	fk_mm_bill,
	subid,
	energy_consum,
	consum_energy_price,
	service_price,
	advance_price,
	from_fin_balance,
	to_pay,
	status
) SELECT $1, $2, COALESCE(MAX(subid), 0) + 1, $3, $4, $5, $6, $7, $8, $9
	FROM sm_bill
	WHERE fk_sm = $1
RETURNING id, fk_sm, fk_mm_bill, subid, energy_consum, consum_energy_price, service_price, advance_price, from_fin_balance, to_pay, status
`

type CreateSmBillParams struct {
	FkSm              int32
	FkMmBill          int32
	EnergyConsum      float64
	ConsumEnergyPrice float64
	ServicePrice      pgtype.Float8
	AdvancePrice      float64
	FromFinBalance    float64
	ToPay             float64
	Status            SmBillStatus
}

func (q *Queries) CreateSmBill(ctx context.Context, arg CreateSmBillParams) (SmBill, error) {
	row := q.db.QueryRow(ctx, createSmBill,
		arg.FkSm,
		arg.FkMmBill,
		arg.EnergyConsum,
		arg.ConsumEnergyPrice,
		arg.ServicePrice,
		arg.AdvancePrice,
		arg.FromFinBalance,
		arg.ToPay,
		arg.Status,
	)
	var i SmBill
	err := row.Scan(
		&i.ID,
		&i.FkSm,
		&i.FkMmBill,
		&i.Subid,
		&i.EnergyConsum,
		&i.ConsumEnergyPrice,
		&i.ServicePrice,
		&i.AdvancePrice,
		&i.FromFinBalance,
		&i.ToPay,
		&i.Status,
	)
	return i, err
}

const createSmBillPeriod = `-- name: CreateSmBillPeriod :one
INSERT INTO sm_bill_period (
	fk_sm_bill,
	fk_mm_bill_period,
	energy_consum,
	consum_energy_price,
	service_price,
	advance_price,
	total_price
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
RETURNING id, fk_sm_bill, fk_mm_bill_period, energy_consum, consum_energy_price, service_price, advance_price, total_price
`

type CreateSmBillPeriodParams struct {
	FkSmBill          int32
	FkMmBillPeriod    int32
	EnergyConsum      float64
	ConsumEnergyPrice float64
	ServicePrice      pgtype.Float8
	AdvancePrice      float64
	TotalPrice        float64
}

func (q *Queries) CreateSmBillPeriod(ctx context.Context, arg CreateSmBillPeriodParams) (SmBillPeriod, error) {
	row := q.db.QueryRow(ctx, createSmBillPeriod,
		arg.FkSmBill,
		arg.FkMmBillPeriod,
		arg.EnergyConsum,
		arg.ConsumEnergyPrice,
		arg.ServicePrice,
		arg.AdvancePrice,
		arg.TotalPrice,
	)
	var i SmBillPeriod
	err := row.Scan(
		&i.ID,
		&i.FkSmBill,
		&i.FkMmBillPeriod,
		&i.EnergyConsum,
		&i.ConsumEnergyPrice,
		&i.ServicePrice,
		&i.AdvancePrice,
		&i.TotalPrice,
	)
	return i, err
}

const getSmRdgs = `-- name: GetSmRdgs :many
WITH selected_sm AS (
	SELECT sm.id
	FROM sm
	WHERE fk_mm = $1
)
SELECT later_rdg.sm_id, sm_rdg.rdg_val, sm_rdg.rdg_date
FROM (
	SELECT selected_sm.id AS sm_id, min(sm_rdg.rdg_date) AS rdg_date
	FROM selected_sm
	JOIN sm_rdg
	ON selected_sm.id = sm_rdg.fk_sm
	WHERE sm_rdg.rdg_date > $2
	GROUP BY selected_sm.id
) later_rdg
LEFT JOIN sm_rdg
	ON later_rdg.sm_id = sm_rdg.fk_sm AND later_rdg.rdg_date = sm_rdg.rdg_date
UNION
SELECT selected_sm.id AS sm_id, sm_rdg.rdg_val, sm_rdg.rdg_date
FROM selected_sm
JOIN sm_rdg
	ON selected_sm.id = sm_rdg.fk_sm
WHERE sm_rdg.rdg_date BETWEEN $3 AND $2
UNION
SELECT selected_sm.id AS sm_id, sm_rdg.rdg_val, earlier_rdg.rdg_date
FROM selected_sm
LEFT JOIN (
	SELECT selected_sm.id AS sm_id, max(sm_rdg.rdg_date) AS rdg_date
	FROM selected_sm
	LEFT JOIN sm_rdg
		ON	selected_sm.id = sm_rdg.fk_sm
	WHERE sm_rdg.rdg_date < $3
	GROUP BY selected_sm.id
) earlier_rdg
	ON selected_sm.id = earlier_rdg.sm_id
LEFT JOIN sm_rdg
	ON earlier_rdg.sm_id = sm_rdg.fk_sm AND earlier_rdg.rdg_date = sm_rdg.rdg_date
ORDER BY rdg_date DESC NULLS LAST
`

type GetSmRdgsParams struct {
	FkMm    int32
	DateMax pgtype.Date
	DateMin pgtype.Date
}

type GetSmRdgsRow struct {
	SmID    int32
	RdgVal  pgtype.Float8
	RdgDate pgtype.Date
}

func (q *Queries) GetSmRdgs(ctx context.Context, arg GetSmRdgsParams) ([]GetSmRdgsRow, error) {
	rows, err := q.db.Query(ctx, getSmRdgs, arg.FkMm, arg.DateMax, arg.DateMin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSmRdgsRow
	for rows.Next() {
		var i GetSmRdgsRow
		if err := rows.Scan(&i.SmID, &i.RdgVal, &i.RdgDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
