// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mm.sql

package spinusdb

import (
	"context"
)

const createMm = `-- name: CreateMm :one
INSERT INTO mm (
	meter_id,
	energy,
	address,
	currency_code,
	fk_user
) VALUES (
	TRIM($1),
	$2,
	TRIM($3),
	UPPER(TRIM($4)),
	$5
)
RETURNING id, meter_id, energy, address, currency_code, fk_user
`

type CreateMmParams struct {
	MeterID      string
	Energy       Energy
	Address      string
	CurrencyCode string
	FkUser       int32
}

func (q *Queries) CreateMm(ctx context.Context, arg CreateMmParams) (Mm, error) {
	row := q.db.QueryRow(ctx, createMm,
		arg.MeterID,
		arg.Energy,
		arg.Address,
		arg.CurrencyCode,
		arg.FkUser,
	)
	var i Mm
	err := row.Scan(
		&i.ID,
		&i.MeterID,
		&i.Energy,
		&i.Address,
		&i.CurrencyCode,
		&i.FkUser,
	)
	return i, err
}

const getMm = `-- name: GetMm :one
SELECT mm.id, mm.meter_id, mm.energy, mm.address, mm.currency_code, mm.fk_user, spinus_user.email
FROM mm
JOIN spinus_user
	ON mm.fk_user = spinus_user.id
WHERE mm.id = $1
LIMIT 1
`

type GetMmRow struct {
	ID           int32
	MeterID      string
	Energy       Energy
	Address      string
	CurrencyCode string
	FkUser       int32
	Email        string
}

func (q *Queries) GetMm(ctx context.Context, id int32) (GetMmRow, error) {
	row := q.db.QueryRow(ctx, getMm, id)
	var i GetMmRow
	err := row.Scan(
		&i.ID,
		&i.MeterID,
		&i.Energy,
		&i.Address,
		&i.CurrencyCode,
		&i.FkUser,
		&i.Email,
	)
	return i, err
}

const listUserMms = `-- name: ListUserMms :many
SELECT id, meter_id, energy, address, currency_code, fk_user
FROM mm
WHERE fk_user = $1
ORDER BY id
`

func (q *Queries) ListUserMms(ctx context.Context, fkUser int32) ([]Mm, error) {
	rows, err := q.db.Query(ctx, listUserMms, fkUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mm
	for rows.Next() {
		var i Mm
		if err := rows.Scan(
			&i.ID,
			&i.MeterID,
			&i.Energy,
			&i.Address,
			&i.CurrencyCode,
			&i.FkUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
