// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mm.sql

package spinusdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMm = `-- name: CreateMm :one
INSERT INTO mm (
	id,
	meter_id,
	energy,
	address,
	currency_code,
	fk_user
) VALUES (
	$1,
	TRIM($2),
	$3,
	TRIM($4),
	UPPER(TRIM($5)),
	$6
)
RETURNING id, created_ts, meter_id, energy, address, currency_code, fk_user
`

type CreateMmParams struct {
	ID           uuid.UUID
	MeterID      string
	Energy       Energy
	Address      string
	CurrencyCode string
	FkUser       uuid.UUID
}

func (q *Queries) CreateMm(ctx context.Context, arg CreateMmParams) (Mm, error) {
	row := q.db.QueryRow(ctx, createMm,
		arg.ID,
		arg.MeterID,
		arg.Energy,
		arg.Address,
		arg.CurrencyCode,
		arg.FkUser,
	)
	var i Mm
	err := row.Scan(
		&i.ID,
		&i.CreatedTs,
		&i.MeterID,
		&i.Energy,
		&i.Address,
		&i.CurrencyCode,
		&i.FkUser,
	)
	return i, err
}

const getMm = `-- name: GetMm :one
SELECT mm.id, mm.created_ts, mm.meter_id, mm.energy, mm.address, mm.currency_code, mm.fk_user, spinus_user.email
FROM mm
JOIN spinus_user
	ON mm.fk_user = spinus_user.id
WHERE mm.id = $1
LIMIT 1
`

type GetMmRow struct {
	ID           uuid.UUID
	CreatedTs    pgtype.Timestamp
	MeterID      string
	Energy       Energy
	Address      string
	CurrencyCode string
	FkUser       uuid.UUID
	Email        string
}

func (q *Queries) GetMm(ctx context.Context, id uuid.UUID) (GetMmRow, error) {
	row := q.db.QueryRow(ctx, getMm, id)
	var i GetMmRow
	err := row.Scan(
		&i.ID,
		&i.CreatedTs,
		&i.MeterID,
		&i.Energy,
		&i.Address,
		&i.CurrencyCode,
		&i.FkUser,
		&i.Email,
	)
	return i, err
}

const listUserMms = `-- name: ListUserMms :many
SELECT id, created_ts, meter_id, energy, address, currency_code, fk_user
FROM mm
WHERE fk_user = $1
ORDER BY created_ts
`

func (q *Queries) ListUserMms(ctx context.Context, fkUser uuid.UUID) ([]Mm, error) {
	rows, err := q.db.Query(ctx, listUserMms, fkUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mm
	for rows.Next() {
		var i Mm
		if err := rows.Scan(
			&i.ID,
			&i.CreatedTs,
			&i.MeterID,
			&i.Energy,
			&i.Address,
			&i.CurrencyCode,
			&i.FkUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
