// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mm_bill.sql

package spinusdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMmBillSms = `-- name: ListMmBillSms :many
SELECT
	sm.id,
	sm.subid,
	sm.meter_id,
	spinus_user.email,
	energy_consum,
	consum_energy_price,
	service_price,
	advance_price,
	from_fin_balance,
	to_pay,
	status
FROM sm_bill
JOIN sm
	ON sm_bill.fk_sm = sm.id
JOIN spinus_user
	ON sm.fk_user = spinus_user.id
WHERE fk_mm_bill = $1
ORDER BY subid
`

type ListMmBillSmsRow struct {
	ID                int32
	Subid             int32
	MeterID           pgtype.Text
	Email             string
	EnergyConsum      float64
	ConsumEnergyPrice float64
	ServicePrice      pgtype.Float8
	AdvancePrice      float64
	FromFinBalance    float64
	ToPay             float64
	Status            SmBillStatus
}

func (q *Queries) ListMmBillSms(ctx context.Context, fkMmBill int32) ([]ListMmBillSmsRow, error) {
	rows, err := q.db.Query(ctx, listMmBillSms, fkMmBill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMmBillSmsRow
	for rows.Next() {
		var i ListMmBillSmsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subid,
			&i.MeterID,
			&i.Email,
			&i.EnergyConsum,
			&i.ConsumEnergyPrice,
			&i.ServicePrice,
			&i.AdvancePrice,
			&i.FromFinBalance,
			&i.ToPay,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMmBills = `-- name: ListMmBills :many
SELECT id, fk_mm, subid, max_day_diff, begin_date, end_date, energy_consum, consum_energy_price, service_price, advance_price, from_fin_balance, to_pay, status
FROM mm_bill
WHERE fk_mm = $1
ORDER BY subid DESC
`

func (q *Queries) ListMmBills(ctx context.Context, fkMm int32) ([]MmBill, error) {
	rows, err := q.db.Query(ctx, listMmBills, fkMm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MmBill
	for rows.Next() {
		var i MmBill
		if err := rows.Scan(
			&i.ID,
			&i.FkMm,
			&i.Subid,
			&i.MaxDayDiff,
			&i.BeginDate,
			&i.EndDate,
			&i.EnergyConsum,
			&i.ConsumEnergyPrice,
			&i.ServicePrice,
			&i.AdvancePrice,
			&i.FromFinBalance,
			&i.ToPay,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
