// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package spinusdb

import ()

type MainMeter struct {
	ID      int32
	MeterID string
	Address string
	FkUser  int32
}

type SpinusUser struct {
	ID       int32
	Username string
	Email    string
	Password string
}
