// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: new_billing.sql

package spinusdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMainMeterBillingPeriod = `-- name: CreateMainMeterBillingPeriod :one
INSERT INTO main_meter_billing_period (
	fk_main_billing,
	subid,
	begin_date,
	end_date,
	max_day_diff,
	begin_reading_value,
	end_reading_value,
	consumed_energy_price,
	service_price
) SELECT $1, COALESCE(MAX(subid), 0) + 1, $2, $3, $4, $5, $6, $7, $8
	FROM main_meter_billing_period
	WHERE fk_main_billing = $1
RETURNING id, fk_main_billing, subid, begin_date, end_date, max_day_diff, begin_reading_value, end_reading_value, consumed_energy_price, service_price
`

type CreateMainMeterBillingPeriodParams struct {
	FkMainBilling       int32
	BeginDate           pgtype.Date
	EndDate             pgtype.Date
	MaxDayDiff          pgtype.Int4
	BeginReadingValue   float64
	EndReadingValue     float64
	ConsumedEnergyPrice float64
	ServicePrice        pgtype.Float8
}

func (q *Queries) CreateMainMeterBillingPeriod(ctx context.Context, arg CreateMainMeterBillingPeriodParams) (MainMeterBillingPeriod, error) {
	row := q.db.QueryRow(ctx, createMainMeterBillingPeriod,
		arg.FkMainBilling,
		arg.BeginDate,
		arg.EndDate,
		arg.MaxDayDiff,
		arg.BeginReadingValue,
		arg.EndReadingValue,
		arg.ConsumedEnergyPrice,
		arg.ServicePrice,
	)
	var i MainMeterBillingPeriod
	err := row.Scan(
		&i.ID,
		&i.FkMainBilling,
		&i.Subid,
		&i.BeginDate,
		&i.EndDate,
		&i.MaxDayDiff,
		&i.BeginReadingValue,
		&i.EndReadingValue,
		&i.ConsumedEnergyPrice,
		&i.ServicePrice,
	)
	return i, err
}

const getSubMeterReadings = `-- name: GetSubMeterReadings :many
SELECT
	sub_meter.id,
	sub_meter_reading.reading_value,
	sub_meter_reading.reading_date
FROM sub_meter
LEFT JOIN sub_meter_reading
	ON sub_meter.id = sub_meter_reading.fk_sub_meter
WHERE fk_main_meter = $1
ORDER BY reading_date DESC
`

type GetSubMeterReadingsRow struct {
	ID           int32
	ReadingValue pgtype.Float8
	ReadingDate  pgtype.Date
}

func (q *Queries) GetSubMeterReadings(ctx context.Context, fkMainMeter int32) ([]GetSubMeterReadingsRow, error) {
	rows, err := q.db.Query(ctx, getSubMeterReadings, fkMainMeter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubMeterReadingsRow
	for rows.Next() {
		var i GetSubMeterReadingsRow
		if err := rows.Scan(&i.ID, &i.ReadingValue, &i.ReadingDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
