// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: new_billing.sql

package spinusdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMainMeterBillingPeriod = `-- name: CreateMainMeterBillingPeriod :one
INSERT INTO main_meter_billing_period (
	fk_main_billing,
	subid,
	begin_date,
	end_date,
	begin_reading_value,
	end_reading_value,
	consumed_energy_price,
	service_price
) SELECT $1, COALESCE(MAX(subid), 0) + 1, $2, $3, $4, $5, $6, $7
	FROM main_meter_billing_period
	WHERE fk_main_billing = $1
RETURNING id, fk_main_billing, subid, begin_date, end_date, begin_reading_value, end_reading_value, consumed_energy_price, service_price
`

type CreateMainMeterBillingPeriodParams struct {
	FkMainBilling       int32
	BeginDate           pgtype.Date
	EndDate             pgtype.Date
	BeginReadingValue   float64
	EndReadingValue     float64
	ConsumedEnergyPrice float64
	ServicePrice        pgtype.Float8
}

func (q *Queries) CreateMainMeterBillingPeriod(ctx context.Context, arg CreateMainMeterBillingPeriodParams) (MainMeterBillingPeriod, error) {
	row := q.db.QueryRow(ctx, createMainMeterBillingPeriod,
		arg.FkMainBilling,
		arg.BeginDate,
		arg.EndDate,
		arg.BeginReadingValue,
		arg.EndReadingValue,
		arg.ConsumedEnergyPrice,
		arg.ServicePrice,
	)
	var i MainMeterBillingPeriod
	err := row.Scan(
		&i.ID,
		&i.FkMainBilling,
		&i.Subid,
		&i.BeginDate,
		&i.EndDate,
		&i.BeginReadingValue,
		&i.EndReadingValue,
		&i.ConsumedEnergyPrice,
		&i.ServicePrice,
	)
	return i, err
}

const createSubMeterBillingPeriod = `-- name: CreateSubMeterBillingPeriod :one
INSERT INTO sub_meter_billing_period (
	fk_sub_billing,
	fk_main_billing_period,
	energy_consumption,
	consumed_energy_payment,
	service_payment,
	advance_payment,
	total_payment
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
RETURNING id, fk_sub_billing, fk_main_billing_period, energy_consumption, consumed_energy_payment, service_payment, advance_payment, total_payment
`

type CreateSubMeterBillingPeriodParams struct {
	FkSubBilling          int32
	FkMainBillingPeriod   int32
	EnergyConsumption     float64
	ConsumedEnergyPayment float64
	ServicePayment        float64
	AdvancePayment        float64
	TotalPayment          float64
}

func (q *Queries) CreateSubMeterBillingPeriod(ctx context.Context, arg CreateSubMeterBillingPeriodParams) (SubMeterBillingPeriod, error) {
	row := q.db.QueryRow(ctx, createSubMeterBillingPeriod,
		arg.FkSubBilling,
		arg.FkMainBillingPeriod,
		arg.EnergyConsumption,
		arg.ConsumedEnergyPayment,
		arg.ServicePayment,
		arg.AdvancePayment,
		arg.TotalPayment,
	)
	var i SubMeterBillingPeriod
	err := row.Scan(
		&i.ID,
		&i.FkSubBilling,
		&i.FkMainBillingPeriod,
		&i.EnergyConsumption,
		&i.ConsumedEnergyPayment,
		&i.ServicePayment,
		&i.AdvancePayment,
		&i.TotalPayment,
	)
	return i, err
}

const getSubMeterReadings = `-- name: GetSubMeterReadings :many
SELECT
	later_reading.id,
	sub_meter_reading.reading_value,
	later_reading.reading_date
FROM (
	SELECT		sub_meter.id,
			min(sub_meter_reading.reading_date) AS reading_date
	FROM		sub_meter
	JOIN		sub_meter_reading
	ON		sub_meter.id = sub_meter_reading.fk_sub_meter
	WHERE		sub_meter.fk_main_meter = $1 AND
			sub_meter_reading.reading_date > $2
	GROUP BY	sub_meter.id
) later_reading
JOIN	sub_meter_reading
ON	later_reading.id = sub_meter_reading.id AND
	later_reading.reading_date = sub_meter_reading.reading_date
UNION
SELECT	sub_meter.id,
	sub_meter_reading.reading_value,
	sub_meter_reading.reading_date
FROM	sub_meter
JOIN	sub_meter_reading
ON	sub_meter.id = sub_meter_reading.fk_sub_meter
WHERE	sub_meter.fk_main_meter = $1 AND
	sub_meter_reading.reading_date BETWEEN $3 AND $2
UNION
SELECT		earlier_reading.id,
		sub_meter_reading.reading_value,
		earlier_reading.reading_date
FROM (
	SELECT		sub_meter.id,
			max(sub_meter_reading.reading_date) AS reading_date
	FROM		sub_meter
	JOIN		sub_meter_reading
	ON		sub_meter.id = sub_meter_reading.fk_sub_meter
	WHERE		sub_meter.fk_main_meter = $1 AND reading_date < $3
	GROUP BY	sub_meter.id
) earlier_reading
RIGHT JOIN	sub_meter_reading
ON		earlier_reading.id = sub_meter_reading.id AND
		earlier_reading.reading_date = sub_meter_reading.reading_date
ORDER BY 	reading_date DESC NULLS LAST
`

type GetSubMeterReadingsParams struct {
	FkMainMeter int32
	DateMax     pgtype.Date
	DateMin     pgtype.Date
}

type GetSubMeterReadingsRow struct {
	ID           int32
	ReadingValue float64
	ReadingDate  pgtype.Date
}

func (q *Queries) GetSubMeterReadings(ctx context.Context, arg GetSubMeterReadingsParams) ([]GetSubMeterReadingsRow, error) {
	rows, err := q.db.Query(ctx, getSubMeterReadings, arg.FkMainMeter, arg.DateMax, arg.DateMin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubMeterReadingsRow
	for rows.Next() {
		var i GetSubMeterReadingsRow
		if err := rows.Scan(&i.ID, &i.ReadingValue, &i.ReadingDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
