// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sm.sql

package spinusdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSm = `-- name: CreateSm :one
INSERT INTO sm (
	id, fk_mm, meter_id, fin_balance, fk_user
) VALUES (
	$1, $2, $3, $4, $5
)
RETURNING id, created_ts, fk_mm, meter_id, fin_balance, fk_user
`

type CreateSmParams struct {
	ID         uuid.UUID
	FkMm       uuid.UUID
	MeterID    pgtype.Text
	FinBalance float64
	FkUser     uuid.UUID
}

func (q *Queries) CreateSm(ctx context.Context, arg CreateSmParams) (Sm, error) {
	row := q.db.QueryRow(ctx, createSm,
		arg.ID,
		arg.FkMm,
		arg.MeterID,
		arg.FinBalance,
		arg.FkUser,
	)
	var i Sm
	err := row.Scan(
		&i.ID,
		&i.CreatedTs,
		&i.FkMm,
		&i.MeterID,
		&i.FinBalance,
		&i.FkUser,
	)
	return i, err
}

const getSm = `-- name: GetSm :one
SELECT
	sm.id,
	sm.fk_mm AS mm_id,
	sm.meter_id,
	sm.fin_balance,
	sm.fk_user AS sub_user_id,
	sub_user.email AS sub_user_email,
	mm.address,
	mm.fk_user AS main_user_id,
	main_user.email AS main_user_email
FROM sm
JOIN mm
	ON sm.fk_mm = mm.id
JOIN spinus_user AS sub_user
	ON sm.fk_user = sub_user.id
JOIN spinus_user AS main_user
	ON mm.fk_user = main_user.id
WHERE sm.id = $1
LIMIT 1
`

type GetSmRow struct {
	ID            uuid.UUID
	MmID          uuid.UUID
	MeterID       pgtype.Text
	FinBalance    float64
	SubUserID     uuid.UUID
	SubUserEmail  string
	Address       string
	MainUserID    uuid.UUID
	MainUserEmail string
}

func (q *Queries) GetSm(ctx context.Context, id uuid.UUID) (GetSmRow, error) {
	row := q.db.QueryRow(ctx, getSm, id)
	var i GetSmRow
	err := row.Scan(
		&i.ID,
		&i.MmID,
		&i.MeterID,
		&i.FinBalance,
		&i.SubUserID,
		&i.SubUserEmail,
		&i.Address,
		&i.MainUserID,
		&i.MainUserEmail,
	)
	return i, err
}

const listSms = `-- name: ListSms :many
SELECT sm.id, sm.created_ts, meter_id, fin_balance, email
FROM sm
JOIN spinus_user
	ON sm.fk_user = spinus_user.id
WHERE fk_mm = $1
ORDER BY sm.created_ts
`

type ListSmsRow struct {
	ID         uuid.UUID
	CreatedTs  pgtype.Timestamp
	MeterID    pgtype.Text
	FinBalance float64
	Email      string
}

func (q *Queries) ListSms(ctx context.Context, fkMm uuid.UUID) ([]ListSmsRow, error) {
	rows, err := q.db.Query(ctx, listSms, fkMm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSmsRow
	for rows.Next() {
		var i ListSmsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedTs,
			&i.MeterID,
			&i.FinBalance,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSmFinBalance = `-- name: UpdateSmFinBalance :exec
UPDATE sm
SET fin_balance = $2
WHERE id = $1
`

type UpdateSmFinBalanceParams struct {
	ID         uuid.UUID
	FinBalance float64
}

func (q *Queries) UpdateSmFinBalance(ctx context.Context, arg UpdateSmFinBalanceParams) error {
	_, err := q.db.Exec(ctx, updateSmFinBalance, arg.ID, arg.FinBalance)
	return err
}
