// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sm.sql

package spinusdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSm = `-- name: CreateSm :one
INSERT INTO sm (
	fk_mm, subid, meter_id, fin_balance, fk_user
) SELECT $1, COALESCE(MAX(subid), 0) + 1, $2, $3, $4
	FROM sm
	WHERE fk_mm = $1
RETURNING id, fk_mm, subid, meter_id, fin_balance, fk_user
`

type CreateSmParams struct {
	FkMm       int32
	MeterID    pgtype.Text
	FinBalance float64
	FkUser     int32
}

func (q *Queries) CreateSm(ctx context.Context, arg CreateSmParams) (Sm, error) {
	row := q.db.QueryRow(ctx, createSm,
		arg.FkMm,
		arg.MeterID,
		arg.FinBalance,
		arg.FkUser,
	)
	var i Sm
	err := row.Scan(
		&i.ID,
		&i.FkMm,
		&i.Subid,
		&i.MeterID,
		&i.FinBalance,
		&i.FkUser,
	)
	return i, err
}

const getSm = `-- name: GetSm :one
SELECT
	sm.id,
	sm.fk_mm AS mm_id,
	sm.subid,
	sm.meter_id AS sm_id,
	sm.fin_balance,
	sm.fk_user AS sub_user_id,
	sub_user.email AS sub_user_email,
	mm.address,
	mm.fk_user AS main_user_id,
	main_user.email AS main_user_email
FROM sm
JOIN mm
	ON sm.fk_mm = mm.id
JOIN spinus_user AS sub_user
	ON sm.fk_user = sub_user.id
JOIN spinus_user AS main_user
	ON mm.fk_user = main_user.id
WHERE fk_mm = $1 AND subid = $2
LIMIT 1
`

type GetSmParams struct {
	FkMm  int32
	Subid int32
}

type GetSmRow struct {
	ID            int32
	MmID          int32
	Subid         int32
	SmID          pgtype.Text
	FinBalance    float64
	SubUserID     int32
	SubUserEmail  string
	Address       string
	MainUserID    int32
	MainUserEmail string
}

func (q *Queries) GetSm(ctx context.Context, arg GetSmParams) (GetSmRow, error) {
	row := q.db.QueryRow(ctx, getSm, arg.FkMm, arg.Subid)
	var i GetSmRow
	err := row.Scan(
		&i.ID,
		&i.MmID,
		&i.Subid,
		&i.SmID,
		&i.FinBalance,
		&i.SubUserID,
		&i.SubUserEmail,
		&i.Address,
		&i.MainUserID,
		&i.MainUserEmail,
	)
	return i, err
}

const listSms = `-- name: ListSms :many
SELECT sm.id, subid, meter_id, fin_balance, email
FROM sm
JOIN spinus_user
	ON sm.fk_user = spinus_user.id
WHERE fk_mm = $1
ORDER BY subid
`

type ListSmsRow struct {
	ID         int32
	Subid      int32
	MeterID    pgtype.Text
	FinBalance float64
	Email      string
}

func (q *Queries) ListSms(ctx context.Context, fkMm int32) ([]ListSmsRow, error) {
	rows, err := q.db.Query(ctx, listSms, fkMm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSmsRow
	for rows.Next() {
		var i ListSmsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subid,
			&i.MeterID,
			&i.FinBalance,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSmFinBalance = `-- name: UpdateSmFinBalance :exec
UPDATE sm
SET fin_balance = $2
WHERE id = $1
`

type UpdateSmFinBalanceParams struct {
	ID         int32
	FinBalance float64
}

func (q *Queries) UpdateSmFinBalance(ctx context.Context, arg UpdateSmFinBalanceParams) error {
	_, err := q.db.Exec(ctx, updateSmFinBalance, arg.ID, arg.FinBalance)
	return err
}
