// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sm_bill.sql

package spinusdb

import (
	"context"
)

const listSmBills = `-- name: ListSmBills :many
SELECT sm_bill.id, sm_bill.fk_sm, sm_bill.fk_mm_bill, sm_bill.subid, sm_bill.energy_consum, sm_bill.consum_energy_price, sm_bill.service_price, sm_bill.advance_price, sm_bill.from_fin_balance, sm_bill.to_pay, sm_bill.status
FROM sm_bill
JOIN sm
	ON sm_bill.fk_sm = sm.id
WHERE fk_mm = $1
ORDER BY sm_bill.subid DESC
`

func (q *Queries) ListSmBills(ctx context.Context, fkMm int32) ([]SmBill, error) {
	rows, err := q.db.Query(ctx, listSmBills, fkMm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmBill
	for rows.Next() {
		var i SmBill
		if err := rows.Scan(
			&i.ID,
			&i.FkSm,
			&i.FkMmBill,
			&i.Subid,
			&i.EnergyConsum,
			&i.ConsumEnergyPrice,
			&i.ServicePrice,
			&i.AdvancePrice,
			&i.FromFinBalance,
			&i.ToPay,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
