// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sm_bill.sql

package spinusdb

import (
	"context"

	"github.com/google/uuid"
)

const listSmBills = `-- name: ListSmBills :many
SELECT id, created_ts, fk_sm, fk_mm_bill, energy_consum, consum_energy_price, service_price, advance_price, from_fin_balance, to_pay, status
FROM sm_bill
WHERE fk_sm = $1
ORDER BY created_ts DESC
`

func (q *Queries) ListSmBills(ctx context.Context, fkSm uuid.UUID) ([]SmBill, error) {
	rows, err := q.db.Query(ctx, listSmBills, fkSm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmBill
	for rows.Next() {
		var i SmBill
		if err := rows.Scan(
			&i.ID,
			&i.CreatedTs,
			&i.FkSm,
			&i.FkMmBill,
			&i.EnergyConsum,
			&i.ConsumEnergyPrice,
			&i.ServicePrice,
			&i.AdvancePrice,
			&i.FromFinBalance,
			&i.ToPay,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
