// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sm_rdg.sql

package spinusdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSmRdg = `-- name: CreateSmRdg :one
INSERT INTO sm_rdg (
	fk_sm, subid, rdg_val, rdg_date
) SELECT $1, COALESCE(MAX(subid), 0) + 1, $2, $3
	FROM sm_rdg
	WHERE fk_sm = $1
RETURNING id, fk_sm, subid, rdg_val, rdg_date
`

type CreateSmRdgParams struct {
	FkSm    int32
	RdgVal  float64
	RdgDate pgtype.Date
}

func (q *Queries) CreateSmRdg(ctx context.Context, arg CreateSmRdgParams) (SmRdg, error) {
	row := q.db.QueryRow(ctx, createSmRdg, arg.FkSm, arg.RdgVal, arg.RdgDate)
	var i SmRdg
	err := row.Scan(
		&i.ID,
		&i.FkSm,
		&i.Subid,
		&i.RdgVal,
		&i.RdgDate,
	)
	return i, err
}

const getSmRdgForDate = `-- name: GetSmRdgForDate :one
SELECT 1
FROM sm_rdg
WHERE fk_sm = $1 AND rdg_date = $2
LIMIT 1
`

type GetSmRdgForDateParams struct {
	FkSm    int32
	RdgDate pgtype.Date
}

func (q *Queries) GetSmRdgForDate(ctx context.Context, arg GetSmRdgForDateParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSmRdgForDate, arg.FkSm, arg.RdgDate)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listSmRdgs = `-- name: ListSmRdgs :many
SELECT id, fk_sm, subid, rdg_val, rdg_date
FROM sm_rdg
WHERE fk_sm = $1
ORDER BY rdg_date DESC
`

func (q *Queries) ListSmRdgs(ctx context.Context, fkSm int32) ([]SmRdg, error) {
	rows, err := q.db.Query(ctx, listSmRdgs, fkSm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmRdg
	for rows.Next() {
		var i SmRdg
		if err := rows.Scan(
			&i.ID,
			&i.FkSm,
			&i.Subid,
			&i.RdgVal,
			&i.RdgDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
