apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
