apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chart.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{ if ( .Files.Get "configmap.yaml") -}}
      annotations: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: "postgres:alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', 'until pg_isready --host {{ .Values.postgres.host }} --port {{ .Values.postgres.port }} --dbname {{ .Values.postgres.name }} --username {{.Values.postgres.username }}; do sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/local-conf.yaml
              subPath: local.yaml
            - name: config
              mountPath: /app/sqlc.yaml
              subPath: sqlc.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "chart.fullname" . }}
